# Generated by Django 3.1.1 on 2020-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='image_URL',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AlterField(
            model_name='listing',
            name='catagory',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('furniture', 'Furniture'), ('auto', 'Auto'), ('electronics', 'Electronics'), ('games_&_toys', 'Games & Toys'), ('appliances', 'Appliances'), ('books', 'Books')], max_length=14),
        ),
    ]
